receivers:
  kafka:
    brokers: # (default = localhost:9092): The list of kafka brokers
      - kafka-1:9092 
      - kafka-2:9092
    topic: otlp_metrics # (default = otlp_spans for traces, otlp_metrics for metrics, otlp_logs for logs): The name of the kafka topic to export to.
    protocol_version: 2.0.0

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  prometheus:
    endpoint: collector:6666
    namespace: default
service:
  pipelines:
    metrics:
      receivers: [kafka]
      processors: [batch]
      exporters: [prometheus]
  telemetry:
    logs:
      level: debug
